### PR TITLE
Unreference socket

### PR DESCRIPTION
**Pull request by DoHe**
Stops retrying from preventing nightwatch process from finishing

### CODE REVIEW

**Comment by NickStefan** [comment]
I merged this because it seemed harmless enough, but both on node 6 (locally) and on nightwatches ci (node 12 i think), it got an error:

https://travis-ci.org/nightwatchjs/nightwatch/builds/176130387

I un-merged it for now. I did some quick looking into node docs and that method "should" be there on a socket. Not sure

**Comment by DoHe** [comment]
This is very strange. As you said and as it says in the [docs](https://nodejs.org/api/net.html#net_socket_unref) it's in the current node version (7.1.0) and has been there since 0.9.1.

**Comment by DoHe** [comment]
Could it be that nock mocks the socket with an object that does not have an `unref` method?

**Comment by NickStefan** [comment]
That must be it. Nock might not make an `unref` method. I'm adding it back with a safeguard.

**Pull request merged**
